//! `nixos:NAME` — a package in the machine's **system configuration**, not in a profile (`J5`).
//!
//! **Why this is not the `nix:` backend with a flag.** `nix profile install` is right for the
//! Nix package manager wherever it runs — a Mac, an Ubuntu box, a NixOS box where somebody wants
//! a scratch tool for one account. On NixOS it is also a *side door*: the profile sits outside
//! the system generation, no `nixos-rebuild` accounts for it, and the machine ends up with two
//! sources of truth. `nixos:` is the other answer — the package goes in the configuration NixOS
//! itself reads, and an install becomes a system generation.
//!
//! Two prefixes rather than one word whose meaning changes per host (owner ruling, 2026-08-16).
//! A NixOS user may legitimately want both, and only two names can say so; and a config file
//! shared across machines keeps meaning the same thing everywhere, which one name could not.
//!
//! **Shall owns one file and never rewrites yours.** `shall-packages.nix` is regenerated from
//! the model; `configuration.nix` gets at most one `imports` line, appended once and guarded, and
//! is otherwise never touched. Parsing a hand-edited Nix expression to edit it in place is a
//! language problem with an ugly failure mode, and it buys nothing. The shape is `pacman`'s repo
//! support one directory over: write `/etc/pacman.d/shall-<name>.conf`, add one `Include =` line,
//! never rewrite the body.
//!
//! **What is proven and what is not.** The renderer below is pure and hermetically tested, and
//! its output is checked as *valid Nix* by `nix-instantiate --parse` — the risk that matters,
//! since a file nix cannot parse breaks the user's whole system configuration rather than just
//! Shall. `nixos-rebuild switch` against a real NixOS is argv-checked and **not executed**: no
//! container available is NixOS (`nixos/nix` is the package manager on a minimal base — no
//! `/etc/NIXOS`, no `nixos-rebuild`, no systemd), and that bound is recorded in `J5` rather than
//! left for a green suite to imply.

use crate::core::{
    BackendCore, CommandExecutor, Error, Installable, MetadataProvider, Package, PackageSpec,
    Queryable, Result,
};
use async_trait::async_trait;
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use tracing::{debug, info};

/// The file Shall generates and owns outright.
pub const GENERATED: &str = "shall-packages.nix";

/// The marker that says this machine *is* NixOS rather than merely having Nix on it.
///
/// `/etc/NIXOS` is the file the installer writes and the one NixOS's own scripts test. Checking
/// for `nix` on `PATH` would be wrong in both directions: a Mac with Nix would answer yes, and
/// the distinction between the two prefixes is exactly what that would erase.
const MARKER: &str = "/etc/NIXOS";

/// The header on the generated file. A user who opens it should learn, in one line, that editing
/// it is pointless — the next sync overwrites it.
const BANNER: &str = "# Generated by Shall. Do not edit: `shall sync` rewrites this file from \
                      your modules.\n# The line that imports it lives in configuration.nix.\n";

/// Everything Shall declares into the system configuration (`J5`: packages, services and the
/// perimeter, not packages alone).
///
/// **One value rather than a parameter list, because two callers write this one file and each
/// knows only its own half.** The package path arrives through `Installable` with a batch of
/// specs and nothing else; the `service:`/`firewall:` path arrives from the model with no
/// packages in hand. Both [`read`] the file back into this shape, change their half and write it
/// whole, so neither can drop the other's — which is the same class of defect as the rollback
/// that restored one of two changed files.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Module {
    pub packages: BTreeSet<String>,
    /// `services.<name>.enable`. A map to a bool rather than a set of names, because
    /// `service:nginx @status=stopped` has to write `false`; a name merely missing from a set
    /// cannot say the difference between *turn this off* and *this is not mine*.
    pub services: BTreeMap<String, bool>,
    pub tcp_ports: BTreeSet<u16>,
    pub udp_ports: BTreeSet<u16>,
    /// `networking.firewall.enable`. `None` writes nothing and leaves NixOS's own default in
    /// place — only `firewall:default/incoming` makes this an answer Shall has.
    pub firewall: Option<bool>,
}

impl Module {
    /// Every port declared here, whatever it is spoken over. The guard and the lockout check ask
    /// about ports, not about protocols.
    pub fn ports(&self) -> impl Iterator<Item = (u16, crate::model::firewall::Proto)> + '_ {
        use crate::model::firewall::Proto;
        self.tcp_ports
            .iter()
            .map(|p| (*p, Proto::Tcp))
            .chain(self.udp_ports.iter().map(|p| (*p, Proto::Udp)))
    }
}

/// Render the whole file from the declared model.
///
/// Pure, and takes the *complete* model rather than a delta: the file is a projection, so there
/// is no state here to get out of step. Sorted throughout, because a generated file that
/// reorders itself produces a diff on every sync and a rebuild that changes nothing.
///
/// **A name this cannot prove safe is refused, not interpolated.** `nixos-rebuild` evaluates
/// this file as root, so a package or service name carrying Nix syntax would rewrite what the
/// rebuild evaluates — one adopted line away from editing boot configuration. Every name here
/// is only ever an identifier or an attribute path of identifiers; anything else is refused by
/// name rather than escaped and hoped over.
pub fn render(m: &Module) -> Result<String> {
    for p in &m.packages {
        validate_attrpath(p).map_err(|why| {
            Error::Validation(format!(
                "`nixos:` cannot render package name `{p}` as Nix: {why}"
            ))
        })?;
    }
    for name in m.services.keys() {
        validate_attrpath(name).map_err(|why| {
            Error::Validation(format!(
                "`nixos:` cannot render service name `{name}` as Nix: {why}"
            ))
        })?;
    }

    let mut out = String::from(BANNER);
    out.push_str("{ config, lib, pkgs, ... }:\n{\n");

    out.push_str("  environment.systemPackages = with pkgs; [\n");
    for p in &m.packages {
        out.push_str("    ");
        out.push_str(p);
        out.push('\n');
    }
    out.push_str("  ];\n");

    for (name, on) in &m.services {
        out.push_str(&format!("  services.{}.enable = {};\n", name, on));
    }
    if let Some(on) = m.firewall {
        out.push_str(&format!("  networking.firewall.enable = {};\n", on));
    }
    for (attr, ports) in [
        ("allowedTCPPorts", &m.tcp_ports),
        ("allowedUDPPorts", &m.udp_ports),
    ] {
        if ports.is_empty() {
            continue;
        }
        let list: Vec<String> = ports.iter().map(|p| p.to_string()).collect();
        out.push_str(&format!(
            "  networking.firewall.{} = [ {} ];\n",
            attr,
            list.join(" ")
        ));
    }

    out.push_str("}\n");
    Ok(out)
}

/// Whether `s` is a Nix attribute path — dot-separated identifiers, which is the only shape a
/// generated name may take. `Err` carries what was wrong, for the refusal to quote.
fn validate_attrpath(s: &str) -> std::result::Result<(), String> {
    if s.is_empty() {
        return Err("it is empty".to_string());
    }
    for component in s.split('.') {
        let ok = component.starts_with(|c: char| c.is_ascii_alphabetic() || c == '_')
            && component
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '\'' | '-'));
        if !ok {
            return Err(format!(
                "`{component}` is not a Nix identifier (letters, digits, `_`, `'`, `-`, \
                 starting with a letter or `_`)"
            ));
        }
    }
    Ok(())
}

/// The model a file this module wrote declares.
///
/// The inverse of [`render`], and the reason the two writers can share one file. It reads only
/// the shapes `render` produces, so a file a user has added to by hand keeps the additions —
/// they are simply not Shall's, and Shall reports and rewrites what it put there.
pub fn read(body: &str) -> Module {
    let mut m = Module::default();
    let mut in_packages = false;
    for line in body.lines() {
        let t = line.trim();
        if t.starts_with("environment.systemPackages") {
            in_packages = true;
            continue;
        }
        if in_packages {
            // **Leaving the block, not leaving the file.** The first version of this reader
            // stopped at the closing bracket, which was correct while packages were the only
            // thing in here and would silently have read back no services and no ports.
            if t == "];" {
                in_packages = false;
            } else if !t.is_empty() && !t.starts_with('#') {
                m.packages.insert(t.to_string());
            }
            continue;
        }
        if let Some(rest) = t.strip_prefix("services.") {
            if let Some((name, value)) = rest.split_once(".enable = ") {
                m.services
                    .insert(name.to_string(), value.trim_end_matches(';') == "true");
            }
            continue;
        }
        if let Some(v) = t.strip_prefix("networking.firewall.enable = ") {
            m.firewall = Some(v.trim_end_matches(';') == "true");
        } else if let Some(v) = t.strip_prefix("networking.firewall.allowedTCPPorts = ") {
            m.tcp_ports = ports_in(v);
        } else if let Some(v) = t.strip_prefix("networking.firewall.allowedUDPPorts = ") {
            m.udp_ports = ports_in(v);
        }
    }
    m
}

/// The numbers in a rendered `[ 22 443 ];` list. Anything that is not a port is dropped rather
/// than guessed at — a hand-edited entry Shall cannot read is one it must not claim to own.
fn ports_in(list: &str) -> BTreeSet<u16> {
    list.trim_end_matches(';')
        .trim()
        .trim_start_matches('[')
        .trim_end_matches(']')
        .split_whitespace()
        .filter_map(|p| p.parse().ok())
        .collect()
}

/// How one `service:` line reaches a NixOS machine: the enable state to declare, and whether a
/// restart is still owed to the init.
///
/// **State is declared; a transition is performed.** `services.<name>.enable` says whether the
/// unit is part of the system, which is exactly what `@enabled=` and `@status=running|stopped`
/// mean — so those are written into the configuration and the imperative call is not made, since
/// `systemctl enable` on NixOS writes to a tree the next generation regenerates. `@status=
/// restarted` is not a state at all: no attribute in a NixOS module can say *restart this now*,
/// and a rebuild restarts only what it changed. It keeps going through the init, as on every
/// other host.
///
/// A line that asks for both directions at once is refused by name. On systemd
/// `@enabled=false @status=running` is expressible — disabled at boot, running now — and on
/// NixOS it is not, so approximating it would be a perimeter nobody can reason about (P7).
pub fn service_routing(
    enabled: Option<&str>,
    status: Option<&str>,
) -> std::result::Result<(Option<bool>, bool), String> {
    use crate::backends::service::ServiceAction as A;

    let acts = crate::backends::service::actions_for(enabled, status);
    let on = acts.iter().any(|a| matches!(a, A::Enable | A::Start));
    let off = acts.iter().any(|a| matches!(a, A::Disable | A::Stop));
    let restart = acts.iter().any(|a| matches!(a, A::Restart));
    if on && off {
        return Err(format!(
            "asks to be both on and off at once (`@enabled={}`, `@status={}`). On NixOS a \
             service is `services.<name>.enable`, one attribute with one answer, so there is no \
             way to write *disabled at boot but running now*. Declare one or the other.",
            enabled.unwrap_or("<unset>"),
            status.unwrap_or("<unset>")
        ));
    }
    Ok((on.then_some(true).or(off.then_some(false)), restart))
}

/// `configuration.nix` with the generated file imported, or `None` when this cannot see a safe
/// place to put it.
///
/// **Appending does not work, and that is the whole reason this function exists.** Nix is an
/// expression language, not a line-oriented config file, so the `pacman.conf` precedent — append
/// one `Include =` line, never rewrite the body — does not carry over. A line added after the
/// closing brace lands *outside* the attribute set. Measured on NixOS 26.05, which is where the
/// first version of this was caught:
///
/// ```text
/// error: syntax error, unexpected '=', expecting end of file
///     7| imports = [ ./shall-packages.nix ];
/// ```
///
/// Two shapes are recognised and nothing else is guessed at:
///
/// 1. an existing `imports = [` list — the new path goes in as its first element, which is where
///    a reader would put it and which cannot disturb the entries already there;
/// 2. otherwise the `{` that opens the body, i.e. the first one *after* the argument pattern's
///    `}:` — an attribute set gains one attribute at the top.
///
/// A file matching neither returns `None` and the caller refuses by name. **The result is also
/// handed to `nix-instantiate --parse` before it is written** (see `parses_as_nix`), because a
/// textual edit to somebody's boot configuration should be checked by the language's own parser
/// and not by the confidence of whoever wrote the string matching.
pub fn with_import(body: &str, generated: &str) -> Option<String> {
    let import = format!("./{}", generated);

    // 1. An existing `imports = [ ... ]`. Insert as the first element.
    if let Some(at) = body.find("imports") {
        if let Some(open) = body[at..].find('[') {
            let cut = at + open + 1;
            return Some(format!("{}\n    {}{}", &body[..cut], import, &body[cut..]));
        }
    }

    // 2. The `{` that opens the body. A NixOS module starts `{ config, pkgs, ... }:` and the
    //    body's brace is the next one, so the argument pattern's braces must be skipped — taking
    //    the first `{` in the file would insert into the parameter list and produce nonsense.
    let after_pattern = body.find("}:").map(|i| i + 2).unwrap_or(0);
    let open = body[after_pattern..].find('{')? + after_pattern;
    Some(format!(
        "{}\n  imports = [ {} ];{}",
        &body[..=open],
        import,
        &body[open + 1..]
    ))
}

/// Whether this process can create a file in `dir`.
///
/// Asked by trying, not by reading permission bits: a mode check has to reason about uid, gid,
/// supplementary groups and the sticky bit, and gets one of them wrong. Creating and removing a
/// probe file answers the question the caller actually has.
fn is_writable(dir: &Path) -> bool {
    let probe = dir.join(format!(".shall-write-probe-{}", std::process::id()));
    match std::fs::write(&probe, b"") {
        Ok(()) => {
            let _ = std::fs::remove_file(&probe);
            true
        }
        Err(_) => false,
    }
}

/// Whether `configuration.nix` already pulls the generated file in.
///
/// Substring rather than an exact line: a user may have written it inside an existing
/// `imports = [ ... ];` list, with their own indentation and neighbours. Appending a second
/// import because the first was formatted unexpectedly is the failure this avoids.
pub fn imports_generated(body: &str) -> bool {
    body.contains(GENERATED)
}

pub struct NixosBackendCore {
    pub executor: CommandExecutor,
    pub name: String,
    /// Where `configuration.nix` and the generated file live. A key rather than a constant so a
    /// flake-based or otherwise relocated configuration is reachable without a Shall release.
    pub config_dir: PathBuf,
    /// Whether Shall may append the one `imports` line to `configuration.nix` (owner ruling: a
    /// setting decides). When false, the line is printed for the user to paste once.
    pub manage_imports: bool,
}

impl NixosBackendCore {
    pub fn new(executor: CommandExecutor, config_dir: PathBuf, manage_imports: bool) -> Self {
        Self {
            executor,
            name: "nixos".to_string(),
            config_dir,
            manage_imports,
        }
    }

    pub fn generated_path(&self) -> PathBuf {
        self.config_dir.join(GENERATED)
    }

    fn configuration_path(&self) -> PathBuf {
        self.config_dir.join("configuration.nix")
    }

    pub fn read_generated(&self) -> String {
        std::fs::read_to_string(self.generated_path()).unwrap_or_default()
    }

    /// The model the generated file currently declares — what a writer changes its own half of.
    pub fn declared(&self) -> Module {
        read(&self.read_generated())
    }

    /// Put `body` at `dest`, escalating if the directory is not ours.
    ///
    /// **`/etc/nixos` is root-owned and `std::fs::write` knows nothing about sudo.** The first
    /// version wrote the generated file directly, and on a real NixOS an ordinary `shall sync`
    /// died with `I/O error: Permission denied (os error 13)` — a true sentence naming neither
    /// the file nor the reason. `needs_root()` governs the COMMANDS the executor runs; it does
    /// nothing for a direct filesystem call.
    ///
    /// Every write goes through the executor, so a dry run records it in its VFS instead of
    /// editing boot configuration — this path used to write for real whenever the parent was
    /// writable, which is how a `--dry-run` could touch `/etc/nixos`.
    ///
    /// The pre-write parse gate for an edited `configuration.nix`. When the machine has
    /// `nix-instantiate`, the edited body must parse before it is written — a textual edit to
    /// somebody's boot configuration is checked by the language's own parser, not by the
    /// confidence of whoever wrote the string matching. No tool on PATH means no gate, and
    /// that is stated rather than hidden.
    async fn refuse_unparsable_nix(&self, path: &Path, edited: &str) -> Result<()> {
        if crate::core::launch::resolve_program("nix-instantiate").is_none() {
            debug!(
                "nix-instantiate is not on PATH; skipping the parse check for {}",
                path.display()
            );
            return Ok(());
        }
        let tmp = tempfile::NamedTempFile::new().map_err(Error::from)?;
        std::fs::write(tmp.path(), edited).map_err(Error::from)?;
        let script = tmp.path().to_path_buf();
        let out = tokio::task::spawn_blocking(move || {
            let mut cmd = std::process::Command::new("nix-instantiate");
            cmd.arg("--parse")
                .arg(&script)
                .stdin(std::process::Stdio::null());
            crate::core::blocking::command_output(&mut cmd)
        })
        .await
        .map_err(|e| Error::Other(e.to_string()))?;
        match out {
            Ok(o) if o.status.success() => Ok(()),
            Ok(o) => Err(Error::Validation(format!(
                "the edited {} does not parse as Nix; nothing was written.\n  {}",
                path.display(),
                String::from_utf8_lossy(&o.stderr).trim()
            ))),
            Err(e) => Err(Error::Other(format!(
                "could not run `nix-instantiate --parse` on {}: {}",
                path.display(),
                e
            ))),
        }
    }

    /// The escalated half stages through a `NamedTempFile`: a random name, created with no
    /// permissions for anyone else. The pid-derived name this replaced sat in a shared
    /// directory long enough for a local user to pre-create it and win the root `install`.
    async fn place(&self, dest: &Path, body: &str) -> Result<()> {
        if let Some(parent) = dest.parent() {
            if parent.exists() && is_writable(parent) {
                return self.executor.write_atomic(dest, body).await;
            }
        }
        let to = dest.display().to_string();
        if self.executor.dry_run {
            // No staging, no install: record what would land and stop there. The run's argv
            // below is diverted by the executor anyway; the VFS entry is what makes later
            // dry-run reads of this path answer as if it were written.
            self.executor.write_atomic(dest, body).await?;
            self.executor
                .run("install", &["-m", "0644", "(staged)", &to], true)
                .await?;
            return Ok(());
        }
        let staged = tempfile::Builder::new()
            .prefix("shall-nixos-")
            .tempfile()
            .map_err(|e| {
                Error::Other(format!(
                    "could not stage a temporary file for {}: {}",
                    dest.display(),
                    e
                ))
            })?;
        std::fs::write(staged.path(), body).map_err(Error::from)?;
        let from = staged.path().display().to_string();
        // `staged` stays alive across the install — dropping it deletes the file the root
        // command is about to read.
        let moved = self
            .executor
            .run("install", &["-m", "0644", &from, &to], true)
            .await;
        drop(staged);
        moved.map(|_| ()).map_err(|e| {
            Error::Other(format!(
                "could not write `{}`, which is root-owned on a NixOS machine: {}",
                dest.display(),
                e
            ))
        })
    }

    /// Remove `dest`, escalating the same way [`place`](Self::place) writes — and reporting
    /// failures instead of swallowing them: an escalated `rm -f` that fails is a file Shall
    /// meant to remove still sitting there, which is a fact the caller needs.
    async fn unplace(&self, dest: &Path) -> Result<()> {
        if let Some(parent) = dest.parent() {
            if parent.exists() && is_writable(parent) {
                return self.executor.remove_file(dest).await;
            }
        }
        let target = dest.display().to_string();
        self.executor.run("rm", &["-f", &target], true).await?;
        Ok(())
    }

    /// Make sure `configuration.nix` imports the generated file, or refuse and say what to add.
    ///
    /// **An absent import is a REFUSAL, not a warning.** Nothing Shall declares reaches the
    /// system until that line is there, so proceeding would run a `nixos-rebuild` that rebuilds
    /// the machine exactly as it was and report an install of a package nobody installed.
    /// Measured on NixOS 26.05 before this refused: `install 1`, `Status: SUCCESS`, 45.9s, and
    /// `hello` nowhere on `PATH`. A green transaction over an untouched machine is the worst
    /// shape a failure takes, and it is the one this function exists to make impossible.
    async fn ensure_import(&self) -> Result<()> {
        let path = self.configuration_path();
        let body = std::fs::read_to_string(&path).unwrap_or_default();
        if imports_generated(&body) {
            return Ok(());
        }
        if body.is_empty() {
            return Err(Error::Validation(format!(
                "`{}` is not there to import `{}` from. Shall writes the generated file and the \
                 import that pulls it in; it does not invent a NixOS configuration.",
                path.display(),
                GENERATED
            )));
        }
        let paste = format!(
            "add this to `{}`, inside the attribute set:\n      imports = [ ./{} ];",
            path.display(),
            GENERATED
        );
        if !self.manage_imports {
            return Err(Error::Validation(format!(
                "`{}` does not import `{}`, so nothing Shall declares would take effect and the \
                 rebuild would report success over an unchanged machine.\n  {}\n  Or set \
                 `[nixos] manage_imports = true` to let Shall do it.",
                path.display(),
                GENERATED,
                paste
            )));
        }
        match with_import(&body, GENERATED) {
            Some(edited) => {
                // The parse gate the comment promised, now real: when the machine has
                // `nix-instantiate`, the edited file must parse before it is written.
                self.refuse_unparsable_nix(&path, &edited).await?;
                self.place(&path, &edited).await?;
                info!("added the `{}` import to {}", GENERATED, path.display());
                Ok(())
            }
            // **A shape this cannot edit is a refusal, never a guess.** Writing something that
            // does not parse would break the machine's whole boot configuration, which is a far
            // worse outcome than asking for one pasted line.
            None => Err(Error::Validation(format!(
                "Shall could not find where to add the import in `{}` — it has no `imports = [` \
                 list and no attribute set this can safely open.\n  {}",
                path.display(),
                paste
            ))),
        }
    }

    /// Write the generated file and switch the system to it.
    ///
    /// **The previous file is restored when the rebuild fails.** Otherwise a rejected
    /// configuration leaves the file claiming a state the running system does not have, and the
    /// next `list` reports packages that are not installed — which is `E6`'s phantom drift, in a
    /// file Shall wrote itself.
    pub async fn write_and_switch(&self, module: &Module) -> Result<()> {
        let path = self.generated_path();
        let previous = self.read_generated();
        let body = render(module)?;
        // Both files this operation touches are remembered, because both have to be put back.
        let config_before = std::fs::read_to_string(self.configuration_path()).ok();

        // **A rebuild that changes nothing still costs minutes.** The package path only gets
        // here when the engine has an install or a removal to run, but `service:` and
        // `firewall:` are projected on every sync whether they have converged or not — so
        // without this a NixOS machine would rebuild itself once per run for ever.
        //
        // The import has to be there too, or this would skip on the one state that looks
        // converged and is not: a file identical to what Shall would write, that nothing
        // imports, has never reached the system.
        if previous == body && config_before.as_deref().map(imports_generated) == Some(true) {
            return Ok(());
        }

        if let Some(parent) = path.parent() {
            // A dry run does not create directories for real.
            if !self.executor.dry_run {
                crate::utils::file::ensure_dir(parent)?;
            }
        }
        self.place(&path, &body).await?;
        self.ensure_import().await?;

        // **`-I nixos-config=` or the rebuild reads somebody else's file.** `nixos-rebuild` takes
        // its configuration from `NIX_PATH`, which pins `nixos-config=/etc/nixos/configuration.nix`
        // — so a bare `nixos-rebuild switch` ignores `[nixos] config_dir` entirely. Measured on
        // NixOS 26.05: with a scratch `config_dir`, the rebuild ran for 45.9s, rebuilt the system
        // from the REAL config, exited 0, and Shall reported an install of a package that was
        // never installed. A green transaction over an untouched machine is the worst shape a
        // failure can take, and it is the one this argument prevents.
        let config = self.configuration_path();
        let nixos_config = format!("nixos-config={}", config.display());
        match self
            .executor
            .run(
                "nixos-rebuild",
                &["switch", "-I", &nixos_config],
                self.needs_root(),
            )
            .await
        {
            Ok(_) => {
                info!(
                    "nixos-rebuild switch: {} package(s), {} service(s), {} port(s) declared",
                    module.packages.len(),
                    module.services.len(),
                    module.tcp_ports.len() + module.udp_ports.len()
                );
                Ok(())
            }
            Err(e) => {
                // **BOTH files, and the second one is why this comment is long.** The first
                // version restored only the generated file and left the `imports` line pointing
                // at it. Measured on NixOS 26.05: after one failed rebuild, `/etc/nixos` held a
                // `configuration.nix` importing a path that no longer existed, so
                // `nixos-rebuild` failed for EVERY later reason too —
                //
                //     error: path '/etc/nixos/shall-packages.nix' does not exist
                //
                // A failed sync left the machine unbuildable until somebody hand-edited it. That
                // is worse than the drift this rollback was written to prevent, and it is the
                // same mistake one file over: restoring what you were thinking about instead of
                // everything you changed.
                //
                // Escalating, because `/etc/nixos` is root-owned and a `std::fs` rollback would
                // silently no-op on the one directory that matters.
                //
                // A restore that itself fails is named in the error: the old message asserted
                // both files "were put back as they were" over steps whose results were thrown
                // away, which is exactly the sentence a reader must not be able to trust.
                let mut unrestored: Vec<String> = Vec::new();
                if previous.is_empty() {
                    if let Err(e) = self.unplace(&path).await {
                        unrestored.push(format!("could not remove {}: {}", path.display(), e));
                    }
                } else if let Err(e) = self.place(&path, &previous).await {
                    unrestored.push(format!("could not restore {}: {}", path.display(), e));
                }
                if let Some(before) = config_before {
                    let config = self.configuration_path();
                    if std::fs::read_to_string(&config).ok().as_deref() != Some(before.as_str()) {
                        if let Err(e) = self.place(&config, &before).await {
                            unrestored.push(format!(
                                "could not restore {}: {}",
                                config.display(),
                                e
                            ));
                        }
                    }
                }
                let restored = if unrestored.is_empty() {
                    "Both files this run touched were put back as they were.".to_string()
                } else {
                    format!(
                        "These restores FAILED — fix them by hand before the next rebuild:\n - {}",
                        unrestored.join("\n - ")
                    )
                };
                Err(Error::Other(format!(
                    "`nixos-rebuild switch` failed: {}\n{}",
                    e, restored
                )))
            }
        }
    }
}

#[async_trait]
impl BackendCore for NixosBackendCore {
    fn name(&self) -> &str {
        &self.name
    }

    /// **This machine IS NixOS**, not "this machine has nix". The two prefixes exist precisely
    /// to keep those apart, so the detector must not blur them.
    fn is_available(&self) -> bool {
        Path::new(MARKER).exists()
    }

    fn probes(&self) -> Vec<String> {
        vec!["nixos-rebuild".into()]
    }

    /// `/etc/nixos` is root-owned and `nixos-rebuild switch` activates a system generation.
    fn needs_root(&self) -> bool {
        true
    }
}

#[async_trait]
impl MetadataProvider for NixosBackendCore {
    async fn get_dependencies(&self, _name: &str) -> Result<Vec<String>> {
        // Nix resolves the closure itself; nothing here to orchestrate.
        Ok(vec![])
    }
}

pub struct NixosInstallable {
    pub core: Arc<NixosBackendCore>,
}

#[async_trait]
impl Installable for NixosInstallable {
    /// One rebuild for the batch, not one per package (`II.19`). A `nixos-rebuild switch` is
    /// minutes; doing it per package would make a five-package sync unusable.
    async fn install(&self, specs: &[PackageSpec], _sudo: bool) -> Result<()> {
        // Read back whole and change one half: the services and ports in this file are the
        // `service:`/`firewall:` path's, and a package install must not take them out.
        let mut module = self.core.declared();
        for spec in specs {
            if spec.options.one("version").is_some() {
                return Err(Error::Validation(format!(
                    "`nixos:{}` carries a version, and a NixOS configuration pins packages by \
                     pinning nixpkgs, not per package. Pin your channel or flake input instead.",
                    spec.name
                )));
            }
            module.packages.insert(spec.name.clone());
        }
        self.core.write_and_switch(&module).await
    }

    async fn remove(
        &self,
        names: &[String],
        _sudo: bool,
        _reaped: crate::app::sync::guard::Reaped,
    ) -> Result<()> {
        let mut module = self.core.declared();
        for n in names {
            module.packages.remove(n);
        }
        self.core.write_and_switch(&module).await
    }
}

pub struct NixosQueryable {
    pub core: Arc<NixosBackendCore>,
}

#[async_trait]
impl Queryable for NixosQueryable {
    fn installed_cache(&self) -> (&crate::core::installed::InstalledListings, &str) {
        (self.core.executor.installed_listings(), &self.core.name)
    }

    /// What the generated file declares — which is what the last successful `nixos-rebuild`
    /// applied, because [`write_and_switch`](NixosBackendCore::write_and_switch) restores the
    /// file when the rebuild fails. Reading the system closure instead would answer in store
    /// paths, which do not map back to the attribute names a manifest is written in.
    async fn fetch_installed(&self) -> Result<Vec<Package>> {
        Ok(self
            .core
            .declared()
            .packages
            .into_iter()
            .map(|name| Package {
                backend: self.core.name.clone(),
                name,
                version: None,
                properties: Default::default(),
            })
            .collect())
    }

    async fn list_manual(&self) -> Result<Vec<Package>> {
        self.fetch_installed().await
    }

    fn manual_source(&self) -> String {
        format!("the `{}` file Shall generates from your modules", GENERATED)
    }

    async fn info(&self, name: &str) -> Result<Option<Package>> {
        Ok(self
            .fetch_installed()
            .await?
            .into_iter()
            .find(|p| p.name == name))
    }
}

pub fn register(
    reg: &mut crate::backends::BackendRegistry,
    exec: &CommandExecutor,
    cfg: &crate::config::Config,
) {
    let core = Arc::new(NixosBackendCore::new(
        exec.clone(),
        cfg.nixos.config_dir.clone(),
        cfg.nixos.manage_imports,
    ));
    reg.register(Arc::new(
        crate::core::BackendCapabilities::builder(core.clone())
            .with_installable(Arc::new(NixosInstallable { core: core.clone() }))
            .with_queryable(Arc::new(NixosQueryable { core: core.clone() }))
            .with_metadata_provider(core.clone())
            .build(),
    ));
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::executor::MockExecutor;
    use dashmap::DashMap;
    use std::sync::Arc;

    /// A dry-run executor over a mock command layer; the VFS handle comes back so tests can
    /// read what the dry run *recorded*.
    fn dry_core() -> (
        NixosBackendCore,
        Arc<DashMap<std::path::PathBuf, String>>,
        Arc<MockExecutor>,
    ) {
        let vfs = Arc::new(DashMap::new());
        let mock = Arc::new(MockExecutor::new(vfs.clone()));
        let exec = CommandExecutor::with_layer(
            true,
            false,
            mock.clone(),
            vfs.clone(),
            Arc::new(DashMap::new()),
        );
        let core = NixosBackendCore::new(
            exec,
            std::env::temp_dir().join("shall-nixos-test-cfg"),
            true,
        );
        (core, vfs, mock)
    }

    /// **A dry run edits boot configuration only in its own imagination.** `place` used to
    /// write with raw `std::fs` whenever the parent was writable — which on a scratch config
    /// dir is always — so `--dry-run` wrote `/etc/nixos` for real.
    #[tokio::test]
    async fn a_dry_run_records_the_generated_file_instead_of_writing_it() {
        let dir = tempfile::tempdir().unwrap();
        let dest = dir.path().join("shall-packages.nix");
        let (core, vfs, _mock) = dry_core();

        core.place(&dest, "BODY").await.expect("places");

        assert!(!dest.exists(), "a dry run must not write the file for real");
        assert_eq!(
            vfs.get(&dest).map(|v| v.value().clone()).as_deref(),
            Some("BODY"),
            "the dry run records what would have landed"
        );
    }

    #[tokio::test]
    async fn the_escalated_half_of_a_dry_run_never_stages_a_real_temp_file() {
        // Parent does not exist, so place() takes the escalation branch: staging + root
        // install. Under a dry run neither may touch the machine.
        let dir = tempfile::tempdir().unwrap();
        let before: Vec<_> = std::fs::read_dir(std::env::temp_dir())
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name())
            .collect();
        let dest = dir.path().join("not-here").join("shall-packages.nix");
        let (core, _vfs, mock) = dry_core();

        core.place(&dest, "BODY")
            .await
            .expect("records the escalation");
        assert!(!dest.exists());

        let after: Vec<_> = std::fs::read_dir(std::env::temp_dir())
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name())
            .collect();
        let new_files: Vec<_> = after
            .iter()
            .filter(|n| !before.contains(n))
            // Files only: parallel tests create and remove *directories* under shared
            // `temp_dir` (the listing-cache fixture among them), and one caught mid-cleanup
            // by this snapshot read exactly like a staged file.
            .filter(|n| n.to_string_lossy().starts_with("shall-"))
            .filter(|n| {
                std::fs::metadata(std::env::temp_dir().join(n))
                    .map(|m| m.is_file())
                    .unwrap_or(false)
            })
            .collect();
        assert!(
            new_files.is_empty(),
            "a dry run staged real temp files: {new_files:?}"
        );
        assert!(
            mock.get_calls()
                .await
                .iter()
                // Substring, not prefix: on Unix an escalated run records
                // `sudo -n install -m 0644 …`, and a prefix match would make this test
                // pass on Windows and root only.
                .any(|c| c.contains("install -m 0644")),
            "the install step is still previewed in the run log"
        );
    }

    #[tokio::test]
    async fn a_dry_run_unplace_removes_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let dest = dir.path().join("shall-packages.nix");
        std::fs::write(&dest, "PREVIOUS").unwrap();
        let (core, _vfs, _mock) = dry_core();

        core.unplace(&dest).await.expect("unplace succeeds");
        assert_eq!(
            std::fs::read_to_string(&dest).unwrap(),
            "PREVIOUS",
            "a dry run does not delete for real"
        );
    }

    #[tokio::test]
    async fn a_real_unplace_still_removes_and_forgives_already_gone() {
        let dir = tempfile::tempdir().unwrap();
        let dest = dir.path().join("shall-packages.nix");
        std::fs::write(&dest, "MANAGED").unwrap();

        let vfs = Arc::new(DashMap::new());
        let mock = Arc::new(MockExecutor::new(vfs.clone()));
        let exec =
            CommandExecutor::with_layer(false, false, mock, vfs.clone(), Arc::new(DashMap::new()));
        let core = NixosBackendCore::new(
            exec,
            std::env::temp_dir().join("shall-nixos-test-cfg"),
            true,
        );

        core.unplace(&dest).await.expect("removes what it placed");
        assert!(!dest.exists(), "the real path removes for real");
        // Already gone is done — that is what makes teardown idempotent.
        core.unplace(&dest).await.expect("second remove is a no-op");
    }

    fn set(items: &[&str]) -> BTreeSet<String> {
        items.iter().map(|s| s.to_string()).collect()
    }

    fn packages(items: &[&str]) -> Module {
        Module {
            packages: set(items),
            ..Module::default()
        }
    }

    /// The shape of the file, pinned. A generated file is an interface: it is read by nix, by a
    /// user opening it, and by [`read`] below.
    #[test]
    fn the_generated_file_is_a_nixos_module_naming_its_packages() {
        let out = render(&packages(&["ripgrep", "jq"])).expect("renders");
        assert!(out.starts_with("# Generated by Shall."), "{out}");
        assert!(out.contains("{ config, lib, pkgs, ... }:"), "{out}");
        assert!(
            out.contains("environment.systemPackages = with pkgs; ["),
            "{out}"
        );
        // Sorted, so a sync that changes nothing produces no diff and no rebuild.
        let rg = out.find("ripgrep").expect("ripgrep");
        let jq = out.find("\n    jq").expect("jq");
        assert!(jq < rg, "the package list is not sorted:\n{out}");
        assert!(out.trim_end().ends_with('}'), "{out}");
    }

    /// **A name this cannot prove safe is refused, not interpolated.** The generated file is
    /// evaluated as root by `nixos-rebuild`; a package or service name carrying Nix syntax
    /// would rewrite what the rebuild evaluates. Names are only ever identifiers here —
    /// `render` refuses everything else by name rather than escaping and hoping.
    #[test]
    fn a_name_carrying_nix_syntax_is_refused_not_interpolated() {
        let hostile_packages = packages(&["hello); boot.kernelParams = [ \"x\" ]; #"]);
        assert!(
            render(&hostile_packages).is_err(),
            "a package name with \
             statement syntax must not reach the generated file"
        );

        let mut hostile_services = Module::default();
        hostile_services.services.insert(
            "nginx.enable = true; security.sudo.wheelNeedsPassword = false; #".to_string(),
            true,
        );
        assert!(render(&hostile_services).is_err());

        // The controls: every legitimate spelling still renders. Dotted attrpaths are how
        // real package sets are named (`nodePackages.typescript`), hyphens are in almost
        // every package name, and services can carry sub-options.
        let legit = packages(&["ripgrep", "nodePackages.typescript", "python311"]);
        assert!(render(&legit).is_ok());
        let mut dotted_service = Module::default();
        dotted_service
            .services
            .insert("nginx.virtualHosts.default".to_string(), true);
        assert!(render(&dotted_service).is_ok());
    }

    /// A model with all of `J5` in it. Every one of these is a NixOS attribute a user could
    /// have written by hand, which is the point: `service:` and `firewall:` are system
    /// configuration on this OS, so Shall writes them where NixOS reads them rather than
    /// issuing `systemctl` and `ufw` calls the next generation forgets.
    #[test]
    fn services_and_ports_are_rendered_where_nixos_reads_them() {
        let out = render(&Module {
            packages: set(&["jq"]),
            services: [("nginx".to_string(), true), ("sshd".to_string(), false)]
                .into_iter()
                .collect(),
            tcp_ports: [22u16, 443].into_iter().collect(),
            udp_ports: [53u16].into_iter().collect(),
            firewall: Some(true),
        })
        .expect("renders");
        assert!(out.contains("services.nginx.enable = true;"), "{out}");
        // A stopped service is `false`, not an omission — see `Module::services`.
        assert!(out.contains("services.sshd.enable = false;"), "{out}");
        assert!(out.contains("networking.firewall.enable = true;"), "{out}");
        assert!(
            out.contains("networking.firewall.allowedTCPPorts = [ 22 443 ];"),
            "{out}"
        );
        assert!(
            out.contains("networking.firewall.allowedUDPPorts = [ 53 ];"),
            "{out}"
        );
    }

    /// An empty model is still a valid module, not an empty file. A truncated import would fail
    /// the user's whole rebuild, and "you removed your last package" must not do that.
    #[test]
    fn an_empty_set_still_renders_a_valid_module() {
        let out = render(&Module::default()).expect("renders");
        assert!(
            out.contains("environment.systemPackages = with pkgs; [\n  ];"),
            "{out}"
        );
        assert!(out.contains("{ config, lib, pkgs, ... }:"), "{out}");
        // Nothing declared is nothing written: an absent `networking.firewall.enable` leaves
        // NixOS's own default alone, and writing `false` would silently open the machine.
        assert!(!out.contains("networking.firewall"), "{out}");
    }

    /// **The round trip over the whole model**, which is what makes one file safe for two
    /// writers. `list` depends on the package half; the `service:`/`firewall:` path depends on
    /// every other field surviving a package install that knows nothing about it.
    #[test]
    fn what_is_rendered_is_what_is_read_back() {
        for want in [
            Module::default(),
            packages(&["curl", "jq", "ripgrep"]),
            Module {
                packages: set(&["jq"]),
                services: [("nginx".to_string(), true), ("sshd".to_string(), false)]
                    .into_iter()
                    .collect(),
                tcp_ports: [22u16, 443].into_iter().collect(),
                udp_ports: [53u16].into_iter().collect(),
                firewall: Some(true),
            },
            Module {
                firewall: Some(false),
                ..Module::default()
            },
        ] {
            assert_eq!(
                read(&render(&want).expect("renders")),
                want,
                "{}",
                render(&want).expect("renders")
            );
        }
    }

    /// The reader leaves the package list where the list ends rather than swallowing the rest of
    /// the module. Without this, `services.nginx.enable = true;` reads back as a package name
    /// and the next write declares a package called `services.nginx.enable`.
    #[test]
    fn the_reader_leaves_the_package_list_where_it_ends() {
        let out = render(&Module {
            packages: set(&["jq"]),
            services: [("nginx".to_string(), true)].into_iter().collect(),
            tcp_ports: [22u16].into_iter().collect(),
            ..Module::default()
        })
        .expect("renders");
        assert_eq!(read(&out).packages, set(&["jq"]));
    }

    /// **The defect this shape exists to prevent.** A package install reads the file back,
    /// changes the package set and writes it whole — so if it could not see the services and
    /// ports, installing one package would silently disable every service Shall declared and
    /// close every port it opened. Same class as the rollback that restored one of two files.
    #[test]
    fn a_package_write_carries_the_services_and_ports_it_knows_nothing_about() {
        let before = Module {
            packages: set(&["jq"]),
            services: [("nginx".to_string(), true)].into_iter().collect(),
            tcp_ports: [22u16].into_iter().collect(),
            udp_ports: [53u16].into_iter().collect(),
            firewall: Some(true),
        };
        let mut after = read(&render(&before).expect("renders"));
        after.packages.insert("ripgrep".to_string());
        let out = read(&render(&after).expect("renders"));
        assert_eq!(out.services, before.services);
        assert_eq!(out.tcp_ports, before.tcp_ports);
        assert_eq!(out.udp_ports, before.udp_ports);
        assert_eq!(out.firewall, before.firewall);
        assert_eq!(out.packages, set(&["jq", "ripgrep"]));
    }

    /// State is declared and a transition is performed — every combination the grammar allows,
    /// not just the two that were reported.
    #[test]
    fn a_service_declaration_is_split_into_what_nix_says_and_what_the_init_does() {
        // The bare line: enable and start, which is one attribute here.
        assert_eq!(service_routing(None, None), Ok((Some(true), false)));
        assert_eq!(service_routing(Some("true"), None), Ok((Some(true), false)));
        assert_eq!(service_routing(Some("yes"), None), Ok((Some(true), false)));
        assert_eq!(service_routing(Some("1"), None), Ok((Some(true), false)));
        assert_eq!(
            service_routing(Some("false"), None),
            Ok((Some(false), false))
        );
        for running in ["running", "started", "start"] {
            assert_eq!(
                service_routing(None, Some(running)),
                Ok((Some(true), false))
            );
        }
        for stopped in ["stopped", "stop"] {
            assert_eq!(
                service_routing(None, Some(stopped)),
                Ok((Some(false), false))
            );
        }
        // A restart is not a state: nothing is declared, and the init still gets the call.
        for restart in ["restarted", "restart"] {
            assert_eq!(service_routing(None, Some(restart)), Ok((None, true)));
        }
        // Both axes agreeing is fine; a restart alongside an enable is both halves.
        assert_eq!(
            service_routing(Some("true"), Some("running")),
            Ok((Some(true), false))
        );
        assert_eq!(
            service_routing(Some("true"), Some("restarted")),
            Ok((Some(true), true))
        );
        // And the one shape this OS cannot express is refused by name rather than guessed.
        let err = service_routing(Some("false"), Some("running")).unwrap_err();
        assert!(err.contains("enable"), "{err}");
        assert!(service_routing(Some("true"), Some("stopped")).is_err());
    }

    /// **Write every shape the renderer can produce, for `nix` to parse.**
    ///
    /// The unit tests above check that the text contains what it should. They cannot check the
    /// thing that actually matters — that it is *valid Nix* — because nothing in a Rust test
    /// suite can parse Nix. So the shapes are written to `target/nix-fixtures/`, and
    /// `scripts/nix-validate.sh` runs `nix-instantiate --parse` over them in a container that
    /// has nix. A file this repo generates and nix rejects would break the user's entire system
    /// configuration, not just Shall, which is why it gets a real parser and not a review.
    ///
    /// Measured non-vacuous: an unbalanced module makes that script report
    /// `error: syntax error, unexpected '}'`.
    #[test]
    fn every_rendered_shape_is_written_for_nix_to_parse() {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("target/nix-fixtures");
        std::fs::create_dir_all(&dir).expect("fixture dir");
        let cases = [
            ("empty", render(&Module::default()).expect("renders")),
            (
                "packages",
                render(&packages(&["ripgrep", "jq", "curl"])).expect("renders"),
            ),
            (
                "everything",
                render(&Module {
                    packages: set(&["ripgrep", "jq"]),
                    services: [("nginx".to_string(), true), ("openssh".to_string(), false)]
                        .into_iter()
                        .collect(),
                    tcp_ports: [22u16, 80, 443].into_iter().collect(),
                    udp_ports: [53u16, 123].into_iter().collect(),
                    firewall: Some(true),
                })
                .expect("renders"),
            ),
            // The firewall turned off is a separate shape: it is the only one that writes
            // `networking.firewall.enable = false;`, and a parser gate that never sees it
            // would not be checking the line a user is most likely to be surprised by.
            (
                "firewall-off",
                render(&Module {
                    firewall: Some(false),
                    ..Module::default()
                })
                .expect("renders"),
            ),
        ];
        for (name, body) in &cases {
            std::fs::write(dir.join(format!("{name}.nix")), body).expect("write fixture");
        }
        // Each case is checked by name rather than by counting the directory: the edited-config
        // fixtures land here too, and a total count would make the two tests fight.
        for (name, _) in &cases {
            assert!(
                dir.join(format!("{name}.nix")).is_file(),
                "{name}.nix was not written for the parser to see"
            );
        }
    }

    /// **The defect a real NixOS caught and every hermetic test missed.** Appending the import
    /// after the closing brace puts it outside the attribute set, and nix refuses the file with
    /// `syntax error, unexpected '='` — which breaks the machine's boot configuration, not just
    /// Shall. These pin the two shapes that are safe to edit.
    #[test]
    fn the_import_goes_inside_the_attribute_set_not_after_it() {
        let plain = "{ config, pkgs, ... }:
{
  system.stateVersion = \"26.05\";
}
";
        let out = with_import(plain, GENERATED).expect("a plain module is editable");
        assert!(imports_generated(&out), "{out}");
        // Inside: the import must come before the closing brace, not after it.
        let imp = out.find(GENERATED).expect("import");
        let close = out.rfind('}').expect("closing brace");
        assert!(
            imp < close,
            "the import landed outside the attribute set:
{out}"
        );
        // And not inside the ARGUMENT pattern, which is the other brace in the file.
        let pattern_end = out.find("}:").expect("argument pattern");
        assert!(
            imp > pattern_end,
            "the import landed in the argument list:
{out}"
        );
    }

    /// The common real shape: a machine that already imports its hardware configuration. The new
    /// path joins that list rather than opening a second `imports`, which nix rejects as a
    /// duplicate attribute.
    #[test]
    fn an_existing_imports_list_gains_an_entry_rather_than_a_second_list() {
        let with_hw = "{ config, pkgs, ... }:
{
  imports = [ ./hardware-configuration.nix ];
  system.stateVersion = \"26.05\";
}
";
        let out = with_import(with_hw, GENERATED).expect("editable");
        assert_eq!(
            out.matches("imports").count(),
            1,
            "a second imports list:
{out}"
        );
        assert!(out.contains("hardware-configuration.nix"), "{out}");
        assert!(out.contains(GENERATED), "{out}");
    }

    /// A file this cannot place the import in is refused, not guessed at. Writing something that
    /// does not parse into somebody's boot configuration is the one outcome worth failing over.
    #[test]
    fn a_shape_with_nowhere_to_put_it_is_refused() {
        assert_eq!(with_import("", GENERATED), None);
        assert_eq!(
            with_import(
                "# just a comment
",
                GENERATED
            ),
            None
        );
    }

    /// Every edited shape is written out for `nix-instantiate --parse`, exactly as the rendered
    /// ones are. The generated file was already covered; the file Shall *edits* was not, which
    /// is precisely where the defect was.
    #[test]
    fn every_edited_configuration_is_written_for_nix_to_parse() {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("target/nix-fixtures");
        std::fs::create_dir_all(&dir).expect("fixture dir");
        let cases = [
            (
                "edited-plain",
                "{ config, pkgs, ... }:
{
  system.stateVersion = \"26.05\";
}
",
            ),
            (
                "edited-with-imports",
                "{ config, pkgs, ... }:
{
  imports = [ ./hardware-configuration.nix ];
  system.stateVersion = \"26.05\";
}
",
            ),
        ];
        for (name, body) in &cases {
            let edited = with_import(body, GENERATED).expect("editable");
            std::fs::write(dir.join(format!("{name}.nix")), edited).expect("write");
        }
    }

    /// The import guard, both ways. A second import line is not harmless — nix errors on a
    /// duplicate attribute — so appending twice would break the machine.
    #[test]
    fn an_existing_import_is_recognised_however_it_was_written() {
        assert!(imports_generated("imports = [ ./shall-packages.nix ];"));
        assert!(imports_generated(
            "  imports = [\n    ./hardware-configuration.nix\n    ./shall-packages.nix\n  ];"
        ));
        assert!(!imports_generated(
            "imports = [ ./hardware-configuration.nix ];"
        ));
    }
}
